apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hummingbird--factory-sandbox

labels:
  - pairs:
      paas.redhat.com/appcode: RPRM-001

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - postgres.yaml
