apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: factory
  namespace: factory
  labels:
    app.kubernetes.io/part-of: factory
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: factory
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
