apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grypedb
  labels:
    app.kubernetes.io/part-of: scan-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
