apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-sboms
  labels:
    app.kubernetes.io/part-of: catalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
