FROM quay.io/hummingbird/go:1.26 AS builder

WORKDIR /src
COPY go.mod go.sum ./
COPY sdk/go/reconciler/go.mod sdk/go/reconciler/
COPY . .

ARG BINARY
RUN CGO_ENABLED=0 go build -o /app ./cmd/${BINARY}/

FROM quay.io/hummingbird-community/static:latest
COPY --from=builder /app /app
ENTRYPOINT ["/app"]
