apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: factory
    includeSelectors: false

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: quay.io/hummingbird/factory-admin
    newTag: latest
