apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: quay.io/hummingbird/factory-receiver
    newTag: dev
  - name: quay.io/hummingbird/factory-dispatcher
    newTag: dev
  - name: quay.io/hummingbird/scan-scanner
    newTag: dev
  - name: quay.io/hummingbird/scan-api
    newTag: dev
  - name: quay.io/hummingbird/scan-syncer
    newTag: dev
  - name: quay.io/hummingbird/scan-db-updater
    newTag: dev
  - name: quay.io/hummingbird/postgresql
    newTag: "18"

patches:
  - target:
      kind: Deployment
      name: scan-dispatcher
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: PG_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: factory-db
                key: uri
          - name: FACTORY_LISTEN_ADDR
            value: ":8080"
          - name: FACTORY_QUEUE_NAME
            value: scan
          - name: RECONCILER_ENDPOINT
            value: http://scan-scanner:8082
          - name: DISPATCH_MAX_CONCURRENCY
            value: "5"
          - name: DISPATCH_BATCH_SIZE
            value: "5"
          - name: DISPATCH_LEASE_DURATION
            value: "5m"
          - name: DISPATCH_INTERVAL
            value: "200ms"
