apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: factory

resources:
  - ../../../workqueue/deploy/kubernetes/base
  - ../../../services/vuln-ingest/deploy/kubernetes/overlays/dev
  - ../../../services/registry-probe/deploy/kubernetes/overlays/dev
  - ../../../services/catalog/deploy/kubernetes/overlays/dev

components:
  - ../../components/postgres
  - ../../components/network-policies

images:
  - name: quay.io/hummingbird/factory-admin
    newTag: dev
  - name: quay.io/hummingbird/postgresql
    newTag: "18"

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: StatefulSet
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
