apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: hummingbird-factory
  namespace: rsturla-tenant
spec:
  displayName: Hummingbird Factory
  description: Software factory platform (workqueue, codegen, rpm-builder)
