apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: workqueue
  namespace: REPLACE_WITH_YOUR_NAMESPACE  # e.g., rsturla-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
spec:
  application: factory
  componentName: workqueue
  source:
    git:
      url: https://github.com/rsturla/factory
      revision: main
      context: workqueue
      dockerfileUrl: workqueue/Containerfile
