apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: registry-probe
    includeSelectors: false

resources:
  - deployment.yaml

images:
  - name: quay.io/hummingbird/registry-probe
    newTag: latest
