FROM python:3.14-slim AS builder

WORKDIR /app

COPY _vendor/factory-workqueue/ /tmp/workqueue-sdk/
RUN pip install --no-cache-dir --prefix=/install /tmp/workqueue-sdk/

COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir --prefix=/install .

FROM python:3.14-slim

COPY --from=builder /install /usr/local
COPY data/ /app/data/

WORKDIR /app
USER 1001
