#!/usr/bin/env python3
"""Vuln-match prototype: match catalog packages against vuln-ingest CVE data."""

import json
import os
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field

import psycopg2
from packaging.version import Version, InvalidVersion


@dataclass
class CatalogPkg:
    purl: str
    name: str
    version: str
    source_name: str
    source_version: str


@dataclass
class Match:
    vuln_id: str
    package_name: str
    source_package: str
    pkg_version: str
    upstream_version: str
    match_type: str
    confidence: str
    flags: list = field(default_factory=list)
    sources: list = field(default_factory=list)
    fixed_version: str = ""


def parse_source_rpm(purl: str, name: str, version: str) -> tuple[str, str]:
    """Extract source RPM name and upstream version from PURL."""
    m = re.search(r'upstream=([^&]+)', purl)
    if not m:
        return name, version.split('-')[0]

    upstream = m.group(1)
    # "php-8.5.6-1.hum1.src.rpm" → name="php", version="8.5.6"
    sm = re.match(r'^(.+?)-(\d.*)\.src\.rpm$', upstream)
    if not sm:
        return name, version.split('-')[0]

    return sm.group(1), sm.group(2).split('-')[0]


def compare_versions(a: str, b: str) -> int:
    """Compare two version strings. Returns -1, 0, or 1."""
    try:
        va, vb = Version(a), Version(b)
        if va < vb: return -1
        if va > vb: return 1
        return 0
    except InvalidVersion:
        pass

    # Fallback: component-wise numeric comparison
    def split(v):
        return re.split(r'[.\-]', v)

    pa, pb = split(a), split(b)
    for i in range(max(len(pa), len(pb))):
        ca = pa[i] if i < len(pa) else "0"
        cb = pb[i] if i < len(pb) else "0"
        try:
            na, nb = int(ca), int(cb)
            if na < nb: return -1
            if na > nb: return 1
        except ValueError:
            if ca < cb: return -1
            if ca > cb: return 1
    return 0


def is_affected(version: str, ranges: list[dict]) -> tuple[bool, str, list[str]]:
    """Check if version is affected by any range. Returns (affected, fixed_version, flags)."""
    if not ranges:
        return False, "", ["no-ranges"]

    # Separate quality tiers
    # fixed="*" means "no fix available" — treat as unbounded (all versions affected)
    with_fix = [r for r in ranges if (r.get('fixed') and r['fixed'] != '*') or r.get('last_affected')]
    all_versions = [r for r in ranges if r.get('fixed') == '*']
    intro_only = [r for r in ranges if r.get('introduced') and not r.get('fixed') and not r.get('last_affected')]

    fixed_ver = ""
    flags = []

    # Check high-quality ranges first
    for r in with_fix:
        intro = r.get('introduced', '')
        fixed = r.get('fixed', '')
        last = r.get('last_affected', '')

        if intro and compare_versions(version, intro) < 0:
            continue

        if fixed:
            if compare_versions(version, fixed) < 0:
                fixed_ver = fixed
                return True, fixed_ver, flags
            # Version >= fixed → not affected by this range
            continue

        if last:
            if compare_versions(version, last) <= 0:
                return True, "", flags

    # fixed=* means all versions affected, no fix available
    if all_versions:
        flags.append("no-fix-available")
        return True, "", flags

    # If high-quality ranges all say "not affected", trust them even if
    # intro-only ranges disagree
    if with_fix:
        return False, "", []

    # Only intro-only ranges — low confidence
    for r in intro_only:
        intro = r.get('introduced', '')
        if intro and compare_versions(version, intro) >= 0:
            flags.append("no-fixed-version")
            return True, "", flags

    return False, "", []


def load_name_mappings(path: str = "mappings.json") -> dict[str, list[str]]:
    """Load reviewed name mappings from JSON file.

    Generated by propose_mappings.py (agent-proposed), reviewed by human.
    Format: {"rpm_name": ["vuln_name1", "vuln_name2"], ...}
    """
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        data = json.load(f)
    if isinstance(data, dict) and "mappings" in data:
        return {
            m["rpm_name"].lower(): [n.lower() for n in m["proposed_names"]]
            for m in data["mappings"]
            if m.get("confidence") in ("high", "medium")
        }
    return {k.lower(): [v.lower() for v in vs] for k, vs in data.items()}


CPE_INDEX = None

def load_cpe_index():
    global CPE_INDEX
    if CPE_INDEX is None:
        try:
            with open("cpe_index.json") as f:
                CPE_INDEX = json.load(f)
        except FileNotFoundError:
            CPE_INDEX = {}
    return CPE_INDEX


def name_variants(src_name: str, vuln_index_keys: set, extra_mappings: dict) -> list[str]:
    """Generate name variants dynamically.

    Uses pattern-based generation + reviewed mappings from mappings.json.
    No hardcoded mappings in code.
    """
    name = src_name.lower()
    candidates = {name}

    # Reviewed mappings (agent-proposed, human-approved)
    if name in extra_mappings:
        candidates.update(extra_mappings[name])

    # Strip lib prefix
    if name.startswith('lib') and len(name) > 3:
        candidates.add(name[3:])
    if not name.startswith('lib'):
        candidates.add('lib' + name)

    # Strip trailing version numbers: python3.14 → python
    stripped = re.sub(r'\d+(\.\d+)*$', '', name)
    if stripped and stripped != name:
        candidates.add(stripped)
        candidates.add(stripped.rstrip('.'))

    # RPM naming: glib2 → glib
    stripped2 = re.sub(r'\d+$', '', name)
    if stripped2 and stripped2 != name:
        candidates.add(stripped2)

    # Hyphen/underscore variants
    if '-' in name:
        candidates.add(name.replace('-', '_'))
    if '_' in name:
        candidates.add(name.replace('_', '-'))

    # CPE dictionary: lookup product name from CPE
    cpe = load_cpe_index()
    for c in list(candidates):
        if c in cpe:
            _, cpe_product, _ = cpe[c]
            candidates.add(cpe_product.lower())

    return [c for c in candidates if c in vuln_index_keys]


def main():
    catalog_url = "host=localhost port=15433 dbname=catalogdb user=catalogdb password=catalogdb"
    vuln_url = "host=localhost port=15434 dbname=vulndb user=vulndb password=vulndb"
    scan_url = "host=localhost port=15432 dbname=scandb user=scandb password=scandb"

    # Load agent-proposed, human-reviewed mappings
    name_mappings = load_name_mappings()
    if name_mappings:
        print(f"Loaded {len(name_mappings)} name mappings from mappings.json", file=sys.stderr)
    else:
        print("No mappings.json found — using pattern-based matching only", file=sys.stderr)

    # Load catalog packages
    with psycopg2.connect(catalog_url) as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT DISTINCT purl, name, version, type FROM packages WHERE type = 'rpm' ORDER BY name")
            packages = []
            for row in cur.fetchall():
                purl, name, version, typ = row
                src_name, src_ver = parse_source_rpm(purl, name, version)
                packages.append(CatalogPkg(purl, name, version, src_name, src_ver))

    print(f"Catalog: {len(packages)} RPM packages", file=sys.stderr)

    # Group by source package
    by_source = defaultdict(list)
    for p in packages:
        by_source[p.source_name].append(p)
    print(f"Source packages: {len(by_source)}", file=sys.stderr)

    # Build vuln index
    with psycopg2.connect(vuln_url) as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT ap.vuln_id, ap.source, lower(ap.package_name), ap.version_ranges
                FROM affected_packages ap
                WHERE ap.package_name != ''
            """)

            # Group by (vuln_id, package_name)
            vuln_index = defaultdict(lambda: defaultdict(lambda: {"sources": [], "ranges": []}))
            for vuln_id, source, pkg_name, ranges_json in cur.fetchall():
                entry = vuln_index[pkg_name][vuln_id]
                if source not in entry["sources"]:
                    entry["sources"].append(source)
                if ranges_json:
                    ranges = json.loads(ranges_json) if isinstance(ranges_json, str) else ranges_json
                    entry["ranges"].extend(ranges)

    print(f"Vuln index: {len(vuln_index)} package names", file=sys.stderr)

    # Match
    all_matches = []
    for src_name, pkgs in by_source.items():
        upstream_ver = pkgs[0].source_version

        # Try multiple name variants to find CVEs
        cves = {}
        for lookup_name in name_variants(src_name, set(vuln_index.keys()), name_mappings):
            found = vuln_index.get(lookup_name, {})
            for vid, data in found.items():
                if vid not in cves:
                    cves[vid] = data
                else:
                    cves[vid]["sources"] = list(set(cves[vid]["sources"] + data["sources"]))
                    cves[vid]["ranges"].extend(data["ranges"])

        if not cves:
            continue

        for vuln_id, data in cves.items():
            affected, fixed_ver, flags = is_affected(upstream_ver, data["ranges"])
            if not affected:
                continue

            confidence = "low" if "no-fixed-version" in flags else "medium"

            for pkg in pkgs:
                all_matches.append(Match(
                    vuln_id=vuln_id,
                    package_name=pkg.name,
                    source_package=src_name,
                    pkg_version=pkg.version,
                    upstream_version=upstream_ver,
                    match_type="source-name-version",
                    confidence=confidence,
                    flags=flags,
                    sources=data["sources"],
                    fixed_version=fixed_ver,
                ))

    print(f"Matches: {len(all_matches)}", file=sys.stderr)

    # Load Grype findings
    with psycopg2.connect(scan_url) as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT DISTINCT f.vuln_id, f.package_name, f.package_version
                FROM findings f JOIN scans s ON f.scan_id = s.id
                WHERE s.status = 'completed'
            """)
            grype = {f"{r[0]}|{r[1]}" for r in cur.fetchall()}

    print(f"Grype findings: {len(grype)}", file=sys.stderr)

    # Compare
    our_set = {f"{m.vuln_id}|{m.package_name}" for m in all_matches}

    both = our_set & grype
    only_us = our_set - grype
    only_grype = grype - our_set

    print(f"\n=== COMPARISON vs GRYPE ===", file=sys.stderr)
    print(f"Both found:       {len(both)}", file=sys.stderr)
    print(f"Only vuln-match:  {len(only_us)}", file=sys.stderr)
    print(f"Only Grype:       {len(only_grype)}", file=sys.stderr)
    print(f"Grype total:      {len(grype)}", file=sys.stderr)
    print(f"Vuln-match total: {len(our_set)}", file=sys.stderr)

    if grype:
        print(f"Recall:           {len(both)/len(grype)*100:.1f}%", file=sys.stderr)
    if our_set:
        print(f"Precision:        {len(both)/len(our_set)*100:.1f}%", file=sys.stderr)

    # Analyze misses
    if only_grype:
        print(f"\n--- Missed (Grype found, we didn't) ---", file=sys.stderr)
        # Categorize misses
        miss_reasons = defaultdict(list)
        for key in sorted(only_grype)[:30]:
            vuln_id, pkg_name = key.split("|", 1)
            # Check if we matched the CVE at all (maybe different package)
            cve_matched = any(m.vuln_id == vuln_id for m in all_matches)
            if cve_matched:
                miss_reasons["cve-matched-different-pkg"].append(key)
            else:
                miss_reasons["cve-not-found"].append(key)

        for reason, keys in miss_reasons.items():
            print(f"\n  {reason}: {len(keys)}", file=sys.stderr)
            for k in keys[:5]:
                print(f"    {k}", file=sys.stderr)

    # Confidence breakdown
    by_conf = defaultdict(int)
    for m in all_matches:
        by_conf[m.confidence] += 1
    print(f"\n--- Confidence breakdown ---", file=sys.stderr)
    for conf, count in sorted(by_conf.items()):
        print(f"  {conf}: {count}", file=sys.stderr)


if __name__ == "__main__":
    main()
