apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: workqueue-on-pull-request
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rsturla/factory?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "main" &&
      ("workqueue/".pathChanged() || ".tekton/workqueue-".pathChanged())
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
  labels:
    appstudio.openshift.io/application: hummingbird-factory
    appstudio.openshift.io/component: workqueue
    pipelines.appstudio.openshift.io/type: build
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: revision
      value: '{{revision}}'
    - name: pull-request-number
      value: '{{pull_request_number}}'
  pipelineRef:
    name: workqueue-build-pr
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
