apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-ingest-resolver
spec:
  template:
    spec:
      containers:
        - name: resolver
          env:
            - name: LISTEN_ADDR
              value: ":8082"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vulndb
                  key: uri
            - name: BLOB_BACKEND
              value: s3
            - name: BLOB_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: vuln-ingest-s3
                  key: bucket
            - name: BLOB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: vuln-ingest-s3
                  key: endpoint
                  optional: true
            - name: BLOB_REGION
              valueFrom:
                configMapKeyRef:
                  name: vuln-ingest-s3
                  key: region
                  optional: true
            - name: BLOB_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: vuln-ingest-s3
                  key: prefix
                  optional: true
          volumeMounts: []
      volumes: []
